
title: Gardner Self Publication Platform
email: Perseidsadmin@gmail.com
description: Self-publication platform for Treebanks
baseurl: "/GardnerPrototype"
url: "https://tdbuck.github.io/GardnerPrototype" 
twitter_username: PerseidsProject
github_username:  TDBuck
syntax-highlighting: 
  enabled : true
  highlighter: rouge
show_downloads: true
markdown: kramdown
destination: docs
gems: 
  - jekyll-feed
  - jekyll-coffeescript

theme: "jekyll-theme-slate"
gems: [ jekyll-watch, jekyll-assets]

exclude:
  - Gemfile
  - Gemfile.lock

# below are the changes you will need to make to the config file to make the widget and collections work 

assets:
  assets:
    - "*.json"
    - "*.js"
    - "*.css"
    - "*.png"
    - "*.ttf"
    - "*.svg"
    - "*.eot"
    - "*.otf"
    - "*.woff"
  sources:
    - _assets/arethusa
collections:
  tbpages:
    output: true
    permalink: :title.html